name: flutter_mobile
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: 0.5.28+1
  http: ^0.12.0
  charts_flutter: ^0.9.0
  permission_handler: 5.0.1+1
  cupertino_icons: ^1.0.0
  agora_rtc_engine: ^3.1.3
  #firebase_ml_vision: ^0.9.9
  #camera: ^0.5.8
  flutter_camera_ml_vision: ^2.2.4
  #flutter_blue: ^0.7.3
  sqflite: ^1.3.0
  path: ^1.7.0
  uuid: 2.2.2
  flutter_secure_storage:
  datetime_picker_formfield: ^1.0.0
  provider: ^4.0.2
  path_provider: ^1.6.0
  intl: ^0.16.1
  auto_size_text: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^0.1.9

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  assets:
    - assets/images/sheep.png
    - assets/images/truck.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
